### ISSUE TITLE
Why do I always get an error: URI scheme is not registered for: "com.iancrypto.coinbase-oauth"

### ISSUE THREAD

**Issue by ianfreelancemail** [coinbase/coinbase-ios-sdk#61]
I don't know why I always got that error. In fact I registered the redirect URI in the Coinbase API app and I used the correct Client ID and Secret Key.

My Bundle Identifier: _**com.iancrypto**_
My URL Scheme:  _**com.iancrypto.coinbase-oauth://coinbase-oauth**_
My Registered Redirect URI (Coinbase API):  **_com.iancrypto.coinbase-oauth://coinbase-oauth_**

Please help me correct this if there's an error. If there's something wrong with those details  I stated above, please  help me correct it.

**Comment by ianfreelancemail** [comment]
I really need your help with regards to this issue.

**Comment by soolaymahn** [comment]
Did you register your URI scheme in Xcode? https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app

**Comment by jwitcig** [comment]
Thanks for the suggestion @soolaymahn!

Unfortunately since we are [sunsetting the package](https://github.com/coinbase/coinbase-ios-sdk/commit/3548d4612c7d835a6a7b3e444d3cb3a4aef21a75), we will no longer be providing support.

Stack Overflow might be a good place to move the discussion if it is still needed.

Thank you all for your interest!
